#+ summary: List bands in a given genres from DBpedia 
#+ description: List music bands (in English), returning band name and id
#+ endpoint: https://dbpedia.org/sparql
#+ endpoint_in_url: False
#+ enumerate:
#+   - genreId:
#+     - http://dbpedia.org/resource/Rock_music
#+     - http://dbpedia.org/resource/Alternative_rock
#+ transform: {
#+     "bandId": "?bandId",
#+     "bandName": "?bandName$langTag:hide"
#+ }

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX schema: <http://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?bandId ?bandName WHERE {
  ?bandId rdf:type dbo:Band .
  ?bandId dbo:genre ?_genreId_iri .
  ?bandId dbp:name ?bandName .

  FILTER(LANG(?bandName) = "en") .
} LIMIT 100
