#+ summary: List music genres from DBpedia 
#+ description: List music genres (in English) from DBpedia, returning genre name and id
#+ endpoint: https://dbpedia.org/sparql
#+ endpoint_in_url: False
#+ transform: {
#+     "genreId": "?genreId",
#+     "genreName": "?genreName$langTag:hide"
#+ }

PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?genreId ?genreName WHERE {
  ?genreId rdf:type dbo:Genre .
  ?genreId dbp:name ?genreName .

  FILTER(LANG(?genreName) = "en").
} LIMIT 100
